name: Run CIG in Docker Container

on:
  workflow_dispatch: # 手动触发
  push: # 或自动触发（例如每次 push 时）
    branches: [ main, master ]

jobs:
  run-cig:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # 拉取完整提交历史（如果 cig 需要）

    - name: Pull Docker image
      run: docker pull ghcr.io/ivanbeethoven/cn-in-git:master

    - name: Run CIG command with code mount
      run: |
        # 将当前工作目录挂载到容器的 /workspace
        # 注意根据实际情况调整容器内的挂载路径
        docker run \
          -v "$(pwd):/workspace" \
          -w /workspace \           # 设置容器内工作目录
          --rm \                    # 运行后自动删除容器
          ghcr.io/ivanbeethoven/cn-in-git:master \
          cig
