name: Run CIG in Docker Container

on:
  workflow_dispatch: # manual
  push: 
    branches: [ "master" ] # Need Customize.

jobs:
  run-cig:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # pull the full commit.

    - name: Pull Docker image
      run: docker pull ghcr.io/ivanbeethoven/cn-in-git:master

    - name: Run CIG command with code mount
      run: |
        docker run \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          --rm \
          ghcr.io/ivanbeethoven/cn-in-git:master \
          cig
